export { default as Personal } from './Personal'
export { default as Project } from './Project_'
export { default as Skills } from './Skills'
export { default as Blog } from './Blog'
export { default as Experiences } from './Experiences'
export { default as Hobbies } from './Hobbies'
